import { Router } from 'express';
const router = Router();
import { obtenerEquiposActivos, obtenerEquiposBodega, obtenerEquiposBaja, obtenerComputadora, obtenerEquiposPorUsuario, agregarEquipoSimple ,cambiarUsuarioEquipo,eliminarEquipo, darDeBajaEquipo, editarEquipo, agregarEquipo, agregarComponentes, gestionarComponentesEditados, uploadImage, editarEquipoSimple, obtenerComputadoraBodega, obtenerActivoSimple, obtenerBodegaBajaSimple, eliminarEquipoSimple, obtenerEquiposRed, obtenerEquiposRedBodega, obtenerEquiposRedBaja, agregarEquipoRed, obtenerActivoRed, editarEquipoRed, obtenerBodegaBajaRed, pasarActivoABodega, pasarBodegaAActivo } from '../controllers/equipoController.js'; 
import { exportarEquiposActivos, exportarEquiposBaja, exportarEquiposBodega } from '../controllers/exportarController.js';
import upload from '../middlewares/uploadImageMiddleware.js';

router.get('/', obtenerEquiposActivos);
router.get('/bodega', obtenerEquiposBodega);
router.get('/baja', obtenerEquiposBaja);
router.get('/red', obtenerEquiposRed);
router.get('/exportarEquiposActivos', exportarEquiposActivos);
router.get('/exportarEquiposBodega', exportarEquiposBodega);
router.get('/exportarEquiposBaja', exportarEquiposBaja);
router.get('/redbodega', obtenerEquiposRedBodega);
router.get('/redbaja', obtenerEquiposRedBaja);
router.get('/porUsuario/:id_usuario', obtenerEquiposPorUsuario);
router.put('/cambiarUsuario/:equipoId', cambiarUsuarioEquipo);
router.get('/computadora/:id', obtenerComputadora);
router.get('/computadoraBodega/:id', obtenerComputadoraBodega);
router.get('/equipoSimpleActivo/:id', obtenerActivoSimple);
router.get('/equipoRedActivo/:id', obtenerActivoRed);
router.get('/equipoRedBodegaBaja/:id', obtenerBodegaBajaRed);
router.get('/equipoSimple/:id', obtenerBodegaBajaSimple);
router.delete('/computadora/:equipoId', eliminarEquipo);
router.delete('/equipoSimple/:equipoId', eliminarEquipoSimple);
router.put('/darDeBajaEquipo/:equipoId', darDeBajaEquipo);
router.put('/editarEquipo/:equipoId', editarEquipo);
router.put('/editarEquipoSimple/:equipoId', editarEquipoSimple);
router.put('/editarEquipoRed/:equipoId', editarEquipoRed);
router.put('/activoabodega/:equipoId', pasarActivoABodega);
router.put('/bodegaactivo/:equipoId', pasarBodegaAActivo);
router.put('/activoabodega/:equipoId', pasarBodegaAActivo);
router.post("/agregarEquipoComputadora", agregarEquipo);
router.post("/agregarEquipoSimple", agregarEquipoSimple);
router.post("/agregarEquipoRed", agregarEquipoRed);
router.post("/agregarComponentes", agregarComponentes);
router.post("/gestionarComponentes", gestionarComponentesEditados);
router.post("/upload", upload.single("image"), uploadImage);
export default router;