import { Router } from 'express';
const router = Router();
import { obtenerEquiposActivos, obtenerEquiposBodega, obtenerEquiposBaja, obtenerComputadora, obtenerEquiposPorUsuario, agregarEquipoSimple ,cambiarUsuarioEquipo,eliminarEquipo, darDeBajaEquipo, editarEquipo, agregarEquipo, agregarComponentes, gestionarComponentesEditados, uploadImage, editarEquipoSimple, obtenerComputadoraBodega, obtenerActivoSimple, obtenerBodegaBajaSimple, eliminarEquipoSimple } from '../controllers/equipoController.js'; 
import upload from '../middlewares/uploadImageMiddleware.js';

router.get('/', obtenerEquiposActivos);
router.get('/bodega', obtenerEquiposBodega);
router.get('/baja', obtenerEquiposBaja);
router.get('/porUsuario/:id_usuario', obtenerEquiposPorUsuario);
router.put('/cambiarUsuario/:equipoId', cambiarUsuarioEquipo);
router.get('/computadora/:id', obtenerComputadora);
router.get('/computadoraBodega/:id', obtenerComputadoraBodega);
router.get('/equipoSimpleActivo/:id', obtenerActivoSimple);
router.get('/equipoSimple/:id', obtenerBodegaBajaSimple);
router.delete('/computadora/:equipoId', eliminarEquipo);
router.delete('/equipoSimple/:equipoId', eliminarEquipoSimple);
router.put('/darDeBajaEquipo/:equipoId', darDeBajaEquipo);
router.put('/editarEquipo/:equipoId', editarEquipo);
router.put('/editarEquipoSimple/:equipoId', editarEquipoSimple);
router.post("/agregarEquipoComputadora", agregarEquipo);
router.post("/agregarEquipoSimple", agregarEquipoSimple);
router.post("/agregarComponentes", agregarComponentes);
router.post("/gestionarComponentes", gestionarComponentesEditados);
router.post("/upload", upload.single("image"), uploadImage);
export default router;