import { Router } from 'express';
const router = Router();

import perifericos from './perifericoRoutes.js';
import marcas from './marcaRoutes.js';
import modelos from './modeloRoutes.js';
import series from './serieRoutes.js';
import inventarios from './inventarioRoutes.js';
import equipos from './equipoRoutes.js';
import usos from './usoRoutes.js'; 
import usuarios from './usuarioRoutes.js'; 
import discos from './discoRoutes.js'; 
import dominios from './dominioRoutes.js'; 
import ram from './ramRoutes.js'; 
import sistemasoperativos from './sistemaOperativoRoutes.js'; 
import versionesSO from './versionSORoutes.js'; 
import versionesOffice from './versionOfficeRoutes.js'; 
import edificios from './edificioRoutes.js'; 
import ubicaciones from './ubicacionRoutes.js';
import procesadores from './procesadorRoutes.js'; 
import lamparas from './lamparaRoutes.js';

router.use('/perifericos', perifericos);
router.use('/marcas', marcas);
router.use('/modelos', modelos);
router.use('/series', series);
router.use('/inventarios', inventarios);
router.use('/equipos', equipos);
router.use('/usos', usos); 
router.use('/usuarios', usuarios); 
router.use('/discos', discos); 
router.use('/dominios', dominios); 
router.use('/ram', ram); 
router.use('/sistemasoperativos', sistemasoperativos);
router.use('/versionesSO', versionesSO);  
router.use('/versionesOffice', versionesOffice);  
router.use('/edificios', edificios);  
router.use('/ubicaciones', ubicaciones);  
router.use('/procesadores', procesadores);  
router.use('/lamparas', lamparas);  

export default router;